<?php

require '/var/www/token.php';
define('X_API_KEY_TOKEN', GAZILLIONAIRE_TOKEN);
define('FACEBOOK_APP_TOKEN', GAZILLIONAIRE_FACEBOOK_TOKEN);
define('FACEBOOK_APP_TOKEN_DEV', GAZILLIONAIRE_FACEBOOK_TOKEN_DEV);
